### PR TITLE
0.2.0 release

### PR DESCRIPTION
**Pull request by pluradj**
Signed-off-by: Jason Plurad <pluradj@us.ibm.com>

### CODE REVIEW

**Comment by mbrukman** [comment]
Do you have a preview site we can look at?

* https://pluradj.github.io/janusgraph.org/latest/ shows 0.2.0-SNAPSHOT
* https://pluradj.github.io/janusgraph.org/0.2.0/ is not found

**Comment by pluradj** [comment]
https://pluradj.github.io/janusgraph.org/latest/ is active now

**Comment by robertdale** [comment]
Does github ignore files starting with `_`?
404:  https://pluradj.github.io/janusgraph.org/latest/_field_mapping.html
but it's there..  https://github.com/pluradj/docs.janusgraph.org/blob/0.2.0-docs/0.2.0/_field_mapping.html

**Comment by robertdale** [comment]
- https://pluradj.github.io/janusgraph.org/latest/cassandra.html
  - 404: `DataStax AMI Docs`
- https://pluradj.github.io/janusgraph.org/latest/config-ref.html
  - 404: http://sourceforge.net/apps/trac/ganglia/wiki/gmetric_spoofing
    - Correct:  https://github.com/ganglia/monitor-core/wiki/Gmetric-Spoofing
- https://pluradj.github.io/janusgraph.org/latest/elasticsearch.html
  - `dynamic scripting documentation`: remove missing anchor
  - 404: `processors documentation`
- https://pluradj.github.io/janusgraph.org/latest/monitoring.html
  - DNS not found for link `Metrics` pointing to http://metrics.codahale.com/
    - Correct: http://www.dropwizard.io
  - 404: `Override IP:hostname reported to Ganglia`
    - Correct:  https://github.com/ganglia/monitor-core/wiki/Gmetric-Spoofing

**Comment by robertdale** [comment]
Apply this patch and `Field Mapping` will not start with `_` hence will appear!

```
diff --git a/docs/textsearch.txt b/docs/textsearch.txt
index 48fa61df7..a1618faa8 100644
--- a/docs/textsearch.txt
+++ b/docs/textsearch.txt
@@ -106,6 +106,7 @@ mgmt.commit()
 
 Note that some indexing backends (e.g. Solr) may require additional external schema configuration to support and tune indexing non-point properties.
 
+[[field-mapping]]
 == Field Mapping
 
 [[index-local-field-mapping]]
```

**Comment by pluradj** [comment]
https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/ lists some other options for workarounds, but I'd agree that adding the `[[field-mapping]]` should be done also.

**Comment by robertdale** [comment]
@pluradj There's a pattern used in the docs of using `[[ ]]` before every `== `.  This was the only one missing.  We should stick to that pattern.  `git  grep -B 1 "^== "  -- docs`

**Review by mbrukman — APPROVED** [review]
LGTM

**Comment by mbrukman** [comment]
@pluradj — note that you've pushed your branch from https://github.com/janusgraph/docs.janusgraph.org to your fork of https://github.com/JanusGraph/janusgraph.org (which is a different repo); and you've also pushed it to `master` which means you will diverge from upstream `master`.

This is why I recommend in general pushing the preview sites to the `gh-pages` branch, and publishing that branch to website, rather than `master`, so you can always `git push -f` to `gh-pages` without breaking the equivalence of the `master` branches.

**Pull request merged**
