### PR TITLE
docs for the 0.2.3 release

### PR DESCRIPTION
**Pull request by chupman**
Signed-off-by: Chris Hupman <chupman@us.ibm.com>

This was generated based off of JanusGraph/janusgraph#1598

[preview link](https://chupman.github.io/docs.janusgraph.org/0.2.3/index.html)

### CODE REVIEW

**Comment by porunov** [comment]
@chupman as I understand we won't use modernized documentation for `0.2.3` branch? I.e. this PR: https://github.com/JanusGraph/janusgraph/pull/1437

**Comment by chupman** [comment]
@porunov I somehow missed that it was targeting 0.2, but It'll need to be rolled out across all versions at the same time so I think if anything it would happen with the `0.4.0` release, although within the `0.3.2` release might be possible.

Once I can get the vote out I was planning to help review PRs for the 0.3.2 release. If you have specific priorities you'd like me to look at please let me know.

**Comment by porunov** [comment]
@chupman As I understand that PR do next things:
1) Modernize the documentation
2) Merges documentation of `bugfix releases` into a `feature releases`. I.e. we won't have `0.2.0`, `0.2.1`, `0.2.2`, `0.2.3` docs. Instead, we will have only `0.2`, `0.3`, `0.4` and so on docs (like in ElasticSearch docs).

As @farodin91 said that there are not many commits which affect documentation between `0.2` and `0.3` branches. That is why we can merge `0.2` into `0.3` and `0.3` into `master` very fast after merging  https://github.com/JanusGraph/janusgraph/pull/1437 into `0.2`. As I understand we don't need to wait when `0.3.2` or `0.4.0` is released. We can run those modernized documentation right now which will rewrite our current documentation.

I already reviewed all documentation in #1437 against `0.2.2` documentation. I could review this documentation also but it won't make sense if we change our documentation to modernized documentation soon. 

We should decide when we are ready to replace current documentation with https://github.com/JanusGraph/janusgraph/pull/1437 . If we want to replace documentaion this week then we don't need to review this PR. If we want to delay PR https://github.com/JanusGraph/janusgraph/pull/1437 then we should review this PR.

What do you think about it? Should we delay https://github.com/JanusGraph/janusgraph/pull/1437 or merge it this week?

**Comment by chupman** [comment]
@porunov this is the documentation for the 0.2.3 release. I get wanting to get the modernized docs in sooner rather than later, but that PR won't be ready until we can have a preview containing all the doc versions ready to go.

**Comment by porunov** [comment]
The idea is that documentation doesn't change very much between `bugfix releases`. Sometimes it changes and even new features could be added into `bugfix releases`. Fo such situations we just add a note into `feature documentation` that this functionality is available from `x.y.z` release.

For example, if we add a new parameter into `0.2.3` release, we will have a note near that parameter in `0.2` documentation version like `this parameter is available from 0.2.3 version`. In version `0.3` we will remove this not because it isn't actual for that release. I.e. if the user opens documentation `0.2` then the note is shown. If the user opens documentation `0.3` then the note isn't shown.

**Comment by porunov** [comment]
> but that PR won't be ready until we can have a preview containing all the doc versions ready to go.

As I understand after we merge https://github.com/JanusGraph/janusgraph/pull/1437 we can merge it very fast into `0.3` and `master`, so we will have all versions covered.
I.e. we will need to review only documentation changes between `0.2` and `0.3`.

**Comment by porunov** [comment]
My suggestion would be to review https://github.com/JanusGraph/janusgraph/pull/1437 to merge finish it faster so that we update all our documentation instead of making separate PRs for each `bugfix releases`.
I am OK with this PR and will review it if we decide not to update for modernized documentation soon but of course I would like to go to modernized documentation ASAP.

**Comment by chupman** [comment]
@porunov I fully intend to have these discussions and I have some strong opinions on whether or not we even need to post the documentation for bugfix releases rather than the latest for each major release. That being said JanusGraph/janusgraph#1437 is the appropriate place to have those discussions.

We have a current process for documentation which this PR is following. There are additional considerations we have to take into account in regards the release artifacts that need to be tested and discussed. It's really important to me that we get the doc update right. It's really important to me to update the release manager instructions for you and Florian.

I really do appreciate that you help move things along, but I reviewed over 15 separate pull requests last week and I only have so much bandwidth. Please respect that I'm working towards a vote thread today and I do not intend to force the implementation of the documentation update before this release goes out.

**Comment by porunov** [comment]
@chupman Thank you for your work! You are right. No need to hurry on docs update to not mess up.
I will do the review of this PR tomorrow.

**Review by porunov — APPROVED** [review]
LGTM

**Comment by farodin91** [comment]
I would prefer to release all three versions of JanusGraph than push mkdocs forward. So, we need to updated the documentation before it for all new versions.

**Comment by porunov** [comment]
> I would prefer to release all three versions of JanusGraph than push mkdocs forward. So, we need to updated the documentation before it for all new versions.

Sure. I am totally OK with that.

**Review by FlorianHockmann — APPROVED** [review]
LGTM

**Pull request merged**
