### PR TITLE
Hide docs for all SNAPSHOTS versions

### PR DESCRIPTION
**Pull request by mbrukman**
Since *-SNAPSHOT are not actual released versions, but in-progress checkpoints,
we should hide those docs from search engines and crawlers to avoid user
confusion. Users should only be looking at released versions.

### CODE REVIEW

**Review by pluradj — APPROVED** [review]
LGTM

**Comment by mbrukman** [comment]
For future reference, looks like I also updated the `favicon.ico` file in this PR (even though I originally only meant to update `robots.txt` file here, and update the `favicon.ico` separately).

The `favicon.ico` in this PR is the same file as was submitted and reviewed in https://github.com/JanusGraph/janusgraph.org/pull/35 so the change is correct as is.

**Comment by pluradj** [comment]
I had noticed the favicon addition. I figured it was intentional.

**Comment by mbrukman** [comment]
I was going to send a separate PR for just the `favicon.ico` and that's when I realized I already submitted it (I think it was because I had it in my tree, and ran `git add -u` which added all modified files to the commit, rather than just adding the `robots.txt` file to the branch).

So yes, it was intentional to submit it _eventually_, just not in this PR, but it's fine.

**Pull request merged**
