### PR TITLE
0.1.0 release

### PR DESCRIPTION
**Pull request by twilmes**
@mbrukman I went ahead and created the 0.1.0 release docs directory using the version built for the RC in preparation for the formal release. Let me know if there is a different process though when committing to the docs repo.  Thanks!

### CODE REVIEW

**Comment by mbrukman** [comment]
@twilmes — that's basically it. Did you use the [`docs/build-and-copy-docs.sh`](https://github.com/JanusGraph/janusgraph/blob/master/docs/build-and-copy-docs.sh) script from the main JanusGraph repo or did you do this manually?

**Review by mbrukman — APPROVED** [review]
LGTM

**Comment by twilmes** [comment]
I wanted to use the same artifacts as I did for the vote so I did it manually. Granted, a rebuild should reproduce the same thing so I was probably just being paranoid!

**Comment by mbrukman** [comment]
@twilmes – that makes sense, thanks for clarifying.

**Pull request merged**
