### PR TITLE
Fixed TinkerPop links

### PR DESCRIPTION
**Pull request by robertdale**
- Updated incubator links to current.
- Updated path to reference doc.

### CODE REVIEW

**Comment by robertdale** [comment]
- Updated groovy link

**Comment by robertdale** [comment]
Just realized that this is generated content.  Fixed in JanusGraph/janusgraph#46

**Comment by mbrukman** [comment]
@robertdale — that's correct, the HTML files are generated from the text files in the main repo. Sorry for the confusion.

This should be documented; if you'd like to submit a PR to start a README.md file with some basic content including this information, that would be appreciated!

**Comment by pluradj** [comment]
updating the repo description would help too @mbrukman

**Comment by mbrukman** [comment]
@pluradj — I updated repo description to:

> JanusGraph documentation (generated content)

Thoughts?

**Comment by pluradj** [comment]
Add a pointer to the docs source code location, then I think it's all good https://github.com/JanusGraph/janusgraph/tree/master/docs

**Pull request closed without merging**
